language: python
python:
    - 2.7
    - 3.6
    - 3.7
    - 3.8
sudo: false
install:
    - pip install --upgrade pip
    - pip install .[test]
    - pip install pytest-cov codecov traitlets --upgrade
script:
    - py.test --cov=link_traits -v --pyargs link_traits
after_success:
    - py.test --cov=./
    - codecov
matrix:
    allow_failures:
        - python: "nightly"
